#+TITLE: README

* Introduction

Solutions to the exercises from /The C Programming Language/ by Brian Kernighan
and Dennis Ritchie. I will include my own solutions as well as those the
solutions provided by the /The C Answer Book/ by Clovis L. Tondo.

Files with the =answer= prefix in their names are the solutions taken from the
book mentioned above. Files without this prefix are my own solutions.

I will try to provide a list of helpful resources at the the end of the README.

* Rules

+ Write in ANSI C (C89).
+ Be pedantic; turn on essentially all warnings.
    #+begin_src sh
    cc -O0 -std=c89 -Wall -Wextra -Werror -Wformat=2 -Wunused-variable -Wno-implicit-int -Wno-return-type -pedantic
  #+end_src
+ For a given problem, use only techniques that have already been covered. If a
  more convenient technique or function has been mentioned but not yet
  explained, it is permissible to use it.

* Resources
+ [[https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.pdf][The GNU C Reference Manual]]
+ [[https://web.archive.org/web/20220620232735/http://graphics.stanford.edu/~seander/bithacks.html][Bit Twiddling Hacks by Sean Eron Anderson]]
+ [[https://github.com/oz123/awesome-c][Awesome C Projects]]

* To do
+ Add /C Answer Book/ solutions for all exercises in chapter 1, 2 and 3
+ Move functions directly into the sources files so that programs are self-contained
+ Finish exercises :
  + 1-20
  + 1-21
  + 1-23
  + 1-24
